#!/bin/sh
###	if { pidof xss-lock; }; then
###		echo "Locker is already running"
###	else
###		xss-lock -- ~/scripts/keybinds/screenlocks/i3lock-fancy/lock
###	fi

killall xss-lock
xss-lock -- ~/scripts/i3lock-blurry/i3lock-blurry &
