#!/bin/bash
# Dependencies: imagemagick, i3lock-color-git, scrot
# vim:fdm=marker
set -o errexit -o noclobber -o nounset
export LC_ALL=C LANG=C

sdir=$(realpath "$0"); sdir=${sdir%/*}; cd ${sdir} # go to scripts directory
# Source some functions
. ./print_help.sh		# contains `print_help`
. ./parse_args.sh		# contains `parse_args`
. ./bright_dark_settings.sh	# contains `light_bg` and `dark_bg`
. ./location_specific.sh	# contains `location_effect`

# May be removed
font="$(convert -list font | awk "{ a[NR] = \$2 } /family: $(fc-match sans -f "%{family}\n")/ { print a[NR-1]; exit }")"
set -o pipefail

text="Type password to unlock"
hue=(-level 0%,100%,0.5)
effect=(-filter Gaussian \
	-resize 20% \
	-define filter:sigma=1.5 \
	-resize 500.5%)
image="$(mktemp).png"		# determine path for the screenshot
trap 'rm -f "$image"' EXIT	# delete the image when script exits

parse_args "$@"

scrot -z "$image" # take a screenshot

# Some voodoo magic that determines dark/bright value of the center of the image
btest="60" # brightness value to compare to
brightness=$(convert "$image" \
	-gravity center \
	-crop 100x100+0+0 +repage \
	-colorspace hsb \
	-resize 1x1 txt:- \
	| awk -F '[%$]' 'NR==2{gsub(",",""); printf "%.0f\n", $(NF-1)}')

if [ "$brightness" -gt "$btest" ]; then
	light_bg	#bright background with dark text and icons
else
	dark_bg		#dark background with bright text and icons
fi

lockico="${icodir}/padlock.png"

# default way to print text on the image (can change depending on location_effect)
printline=(-font "$font" \
	-pointsize 26 \
	-fill "$fontcolor" \
	-gravity center \
	-annotate +0+160 \
	"$text")

location_effect

convert "$image" "${hue[@]}" "${effect[@]}" "${printline[@]}" "$lockico" -gravity center -composite "$image"

# try to use a forked version of i3lock with parameters for color
if ! i3lock -n -e "${param[@]}" -i "$image" > /dev/null 2>&1; then
    # We have failed, lets get back to stock one
    i3lock -n -e -i "$image"
fi
